### ISSUE TITLE
Wrong calc of Resistance

### ISSUE THREAD

**Issue by Wikibear** [ViliusKraujutis/MQ135#2]
float MQ135::getResistance() {
  int val = analogRead(_pin);
  return ((1023./(float)val) * 5. - 1.)*RLOAD;
}

is wrong must be:

float MQ135::getResistance() {
  int val = analogRead(_pin);
  return ((1023./(float)val) - 1.)*RLOAD;
}

**Comment by ViliusKraujutis** [comment]
ok. Let me fix that :)

**Comment by ViliusKraujutis** [comment]
Fixed. Thanks for the letting me know!

**Comment by ViliusKraujutis** [comment]
Related: https://github.com/GeorgK/MQ135/issues/2
